In [1]:
import pandas as pd
import numpy as np
from pprint import pprint

#import the dataset
dataset = pd.read_csv("/home/karl/Desktop/dnet/compsci/sem5/ml/ML_A-Z/Part_3_Classification/Section_19_Decision_Tree_Classification/Python/zoo.csv", names=['animal_name','hair','feathers','eggs',
                                      'milk','airborne','aquatic','predator','toothed',
                                       'backbone','breathes','venomous',
                                       'fins','legs','tail',
                                       'domestic','catsize','class_type'],header=0)

In [2]:
dataset

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,wallaby,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1,1
97,wasp,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0,6
98,wolf,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
99,worm,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,7
100,wren,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2

In [3]:
dataset.columns

Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type'],
      dtype='object')

In [4]:
dataset["class_type"]

0      1
1      1
2      4
3      1
4      1
      ..
96     1
97     6
98     1
99     7
100    2
Name: class_type, Length: 101, dtype: int64

In [5]:
def entropy(target_col):
    elements,counts = np.unique(target_col,return_counts=True)
    entropy = np.sum([(-counts[i]/np.sum(counts))*np.log2(counts[i]/np.sum(counts)) for i in range(len(elements))])
    print("\n Entropy ",elements,counts,entropy,len(elements))
    return entropy

In [6]:
temp1=entropy(dataset["class_type"])
temp1

 Entropy  [1 2 3 4 5 6 7] [41 20  5 13  4  8 10] 2.390559682294039 7

2.390559682294039

In [7]:
def InfoGain(data,split_attribute_name,target_name="class_type"):
    total_entropy = entropy(data[target_name])
    vals,counts = np.unique(data[split_attribute_name],return_counts=True)
    #cal the weighted entropy
    print("InfoGain",len(vals))
    Weighted_Entropy = np.sum([(counts[i]/np.sum(counts))*entropy(data.where(data[split_attribute_name]==vals[i]).
                                dropna()[target_name])for i in range(len(vals))])
    
    #formula for information gain
    Information_Gain = total_entropy-Weighted_Entropy
    return Information_Gain

In [8]:
vals,counts = np.unique(dataset["class_type"],return_counts=True)
print(vals)
counts

[1 2 3 4 5 6 7]

array([41, 20,  5, 13,  4,  8, 10])

In [9]:
dataset["class_type"]==vals[2]

0      False
1      False
2      False
3      False
4      False
       ...
96     False
97     False
98     False
99     False
100    False
Name: class_type, Length: 101, dtype: bool

In [10]:
dataset.where(dataset["class_type"]==vals[2])

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
dataset.where(dataset["class_type"]==vals[2]).dropna()["class_type"]

62    3.0
76    3.0
80    3.0
90    3.0
91    3.0
Name: class_type, dtype: float64

In [12]:
temp2=entropy(dataset.where(dataset["class_type"]==vals[2]).dropna()["class_type"])
temp2

 Entropy  [3.] [5] 0.0 1

0.0

In [13]:
temp3=[entropy(dataset.where(dataset["class_type"]==vals[i]).dropna()["class_type"]) for i in range(len(vals))]
temp3

 Entropy  [1.] [41] 0.0 1

 Entropy  [2.] [20] 0.0 1

 Entropy  [3.] [5] 0.0 1

 Entropy  [4.] [13] 0.0 1

 Entropy  [5.] [4] 0.0 1

 Entropy  [6.] [8] 0.0 1

 Entropy  [7.] [10] 0.0 1

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [14]:
training_data.columns[:-1]

NameError: name 'training_data' is not defined

In [ ]:
parent_node_class = np.unique(data[target_attribute_name])[np.argmax(np.unique(data[target_attribute_name],
                                                                           return_counts=True)[1])]